using Anbar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Anbar.DAL
{
    public class InventoryInitializer:System.Data.Entity.DropCreateDatabaseIfModelChanges<InventoryContext>
    {
        protected override void Seed(InventoryContext context)
        {
            var ProductCategories = new List<ProductCategory>
            {
                new ProductCategory { CategoryName = "رآکتیو" },
                new ProductCategory { CategoryName = "دیسپرس" },
                new ProductCategory { CategoryName = "مستقیم" },
                new ProductCategory { CategoryName = "گوگردی" },
                new ProductCategory { CategoryName = "خمی" },
                new ProductCategory { CategoryName = "نیل" },
                new ProductCategory { CategoryName = "پیگمنت" },
                new ProductCategory { CategoryName = "مواد تعاونی" }

            };
            ProductCategories.ForEach(a => context.ProductCategories.Add(a));
            context.SaveChanges();

            var IxCodes = new List<IxCode>
            {
                new IxCode { IxCodeName = "آبی" },
        new IxCode { IxCodeName = "بنفش" },
        new IxCode { IxCodeName = "جگری" },
        new IxCode { IxCodeName = "زرد" },
        new IxCode { IxCodeName = "سبز" },
        new IxCode { IxCodeName = "صورتی" },
        new IxCode { IxCodeName = "فسفری" },
        new IxCode { IxCodeName = "فیروزه ای، نیوی، نیل و سرمه ای" },
        new IxCode { IxCodeName = "قرمز" },
        new IxCode { IxCodeName = "کرم و قهوه ای" },
        new IxCode { IxCodeName = "گلدن" },
        new IxCode { IxCodeName = "مشکی" },
        new IxCode { IxCodeName = "نارنجی" },
        new IxCode { IxCodeName = "تکمیل" },
        new IxCode { IxCodeName = "چاپ" },
        new IxCode { IxCodeName = "رنگرزی" },
        new IxCode { IxCodeName = "صنعتی (تصفیه خانه، دیگ بخار...)" },
        new IxCode { IxCodeName = "گوناگون" },
        new IxCode { IxCodeName = "مقدمات" }

            };
            IxCodes.ForEach(a => context.IxCodes.Add(a));
            context.SaveChanges();

            var Inventories = new List<Inventory>
            {
                new Inventory {InventoryName="انبار رنگ اصلی" },
                new Inventory {InventoryName="انبار رنگ فرعی" },
                new Inventory {InventoryName="انبار اصلی مواد" },
                new Inventory {InventoryName="انبار فرعی مواد" }
            };
            Inventories.ForEach(a=>context.Inventories.Add(a));
            context.SaveChanges();


            var Units = new List<Unit>
            {
                new Unit {UnitName = "کیلوگرم" },
                new Unit {UnitName=  "گرم" }
            };
            Units.ForEach(a => context.Units.Add(a));
            context.SaveChanges();

            var Products = new List<Product> {
    new Product {ProductCategoryID=1,UnitID=2,ProductName ="سیباکرون قرمز P-3BA", IxCodeID=9, ProductCode="رق101" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="سیباکرون فیروزه ای P-GR", IxCodeID=8, ProductCode="رف101" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="سیباکرون بنفش P-2R", IxCodeID=2, ProductCode="رب101" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="سیباکرون زرد P-H2G", IxCodeID=4, ProductCode="رز101" },
new Product {ProductCategoryID=1,UnitID=2,ProductName =" قرمز KM-8B", IxCodeID=9, ProductCode="رق102" },
new Product {ProductCategoryID=1,UnitID=2,ProductName =" مشکی KN-B", IxCodeID=12, ProductCode="رم101" },
new Product {ProductCategoryID=1,UnitID=2,ProductName =" آبی KN-R", IxCodeID=1, ProductCode="رآ101" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="دریمارین آبی R-GL", IxCodeID=1, ProductCode="رآ102" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="دریمارین گلدن R-G2R", IxCodeID=11, ProductCode="رگ101" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="دریمارین نارنجی R-RP", IxCodeID=13, ProductCode="رن101" },
new Product {ProductCategoryID=1,UnitID=2,ProductName =" بنفش K-3R", IxCodeID=2, ProductCode="رب102" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="سومازین زرد FG", IxCodeID=4, ProductCode="رز102" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="رمازول مشکی B", IxCodeID=12, ProductCode="رم102" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="رمازول آبی R", IxCodeID=1, ProductCode="رآ103" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="رمازول قهوه ای GR", IxCodeID=10, ProductCode="رک101" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="رمازول قرمز RB", IxCodeID=9, ProductCode="رق103" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="رمازول فیروزه ای G", IxCodeID=8, ProductCode="رف102" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="رمازول زرد R", IxCodeID=4, ProductCode="رز103" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="رمازول زرد 3RS", IxCodeID=4, ProductCode="رز104" },
new Product {ProductCategoryID=1,UnitID=2,ProductName =" سبز KE-4BD", IxCodeID=5, ProductCode="رس101" },
new Product {ProductCategoryID=1,UnitID=2,ProductName =" اسکارلت KE-3G", IxCodeID=13, ProductCode="رن102" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="سیباکرون مشکی P-SG", IxCodeID=12, ProductCode="رم103" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="سیباکرون آبی P-3R", IxCodeID=1, ProductCode="رآ104" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="سیباکرون قهوه ای P-6R", IxCodeID=10, ProductCode="رک102" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="سیباکرون گلدن P-2RN", IxCodeID=11, ProductCode="رگ102" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="سیباکرون نیوی P-2R", IxCodeID=8, ProductCode="رف103" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="سیباکرون نارنجی G-P", IxCodeID=13, ProductCode="رن103" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="رمازول زرد FG", IxCodeID=4, ProductCode="رز105" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="چینی TIAN BLUE R 150%", IxCodeID=1, ProductCode="رآ105" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="چینی TIAN VIOLET 5RN 100%", IxCodeID=2, ProductCode="رب103" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="چینی TIAN T.BLUE GHC 160%", IxCodeID=1, ProductCode="رآ106" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="چینی TIAN YELLOW 4GL 160%", IxCodeID=4, ProductCode="رز106" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="کاوه ULTRAZOL YELLOW 3RS 150%", IxCodeID=4, ProductCode="رز107" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="کاوه ULTRAFIX YELLOW 4GL 200%", IxCodeID=4, ProductCode="رز108" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="کاوه ULTRAFIX YELLOW S4GL 200%", IxCodeID=4, ProductCode="رز109" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="SUN ACTIVE RED RBN 133", IxCodeID=9, ProductCode="رق104" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="کاوه ULTRAZOL BLUE BLUE R 150", IxCodeID=1, ProductCode="رآ107" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="کاوه ULTRAZOL ORANGE 3R", IxCodeID=13, ProductCode="رن104" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="کاوه ULTRAZOL T.BLUE G 150", IxCodeID=1, ProductCode="رآ108" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="کاوه ULTRAZOL VIOLET 5B", IxCodeID=2, ProductCode="رب104" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="کاوه ULTRAZOL BLACK ED CONC", IxCodeID=12, ProductCode="رم104" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="کاوه ULTRAZOL BLACK B 150", IxCodeID=12, ProductCode="رم105" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="چینی TIAN YELLOW 3RS 150%", IxCodeID=4, ProductCode="رز110" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="چینی TIAN N.BLUE KFW 200%", IxCodeID=1, ProductCode="رآ109" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="چینی  BLACK X-MAX", IxCodeID=12, ProductCode="رم106" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="کاوه ULTRAZOL BLACK GSP120", IxCodeID=12, ProductCode="رم107" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="چینی  BLACK DS-NN", IxCodeID=12, ProductCode="رم108" },
new Product {ProductCategoryID=1,UnitID=2,ProductName ="SUNZOL CONC BLACK DN", IxCodeID=12, ProductCode="رم109" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="فورون فیروزه ای S-R 200%", IxCodeID=8, ProductCode="دف101" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="ترازیل مشکی MAW", IxCodeID=12, ProductCode="دم101" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="ترازیل مشکی SRL", IxCodeID=12, ProductCode="دم102" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="ترازیل مشکی LBSN", IxCodeID=12, ProductCode="دم103" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="ترازیل آبی BG", IxCodeID=1, ProductCode="دآ101" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="ترازیل آبی SB-GE", IxCodeID=1, ProductCode="دآ102" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="ترازیل آبی 54895", IxCodeID=1, ProductCode="دآ103" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="ترازیل گلدن 2RS", IxCodeID=11, ProductCode="دگ101" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="ترازیل گلدن R", IxCodeID=11, ProductCode="دگ102" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="ترازیل نیوی SGL", IxCodeID=1, ProductCode="دآ104" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="ترازیل قرمز R", IxCodeID=9, ProductCode="دق101" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="سامارون بنفش 4RS", IxCodeID=2, ProductCode="دب101" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="سامارون زرد GLN [SE]", IxCodeID=4, ProductCode="دز101" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="سامارون یلو براون SLN", IxCodeID=4, ProductCode="دز102" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="سامارون یلو براون HRSL", IxCodeID=4, ProductCode="دز103" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="دیانیکس آبی KRNIS", IxCodeID=1, ProductCode="دآ105" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="دیانیکس آبی F3B", IxCodeID=1, ProductCode="دآ106" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="رزولین صورتی BBLS", IxCodeID=6, ProductCode="دص101" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="رزولین آبی BBLS", IxCodeID=1, ProductCode="دآ107" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="رزولین آبی GRL", IxCodeID=1, ProductCode="دآ108" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="رزولین قرمز FBLN-SE", IxCodeID=9, ProductCode="دق102" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="رزولین زرد 5GL", IxCodeID=4, ProductCode="دز104" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="فورون آبی SE-RLE", IxCodeID=1, ProductCode="دآ109" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="فورون قرمز RD-GL", IxCodeID=9, ProductCode="دق103" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="فورون قرمز S-FL", IxCodeID=9, ProductCode="دق104" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="فورون قرمز SE-GL", IxCodeID=9, ProductCode="دق105" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="فورون روبین SE-GFL", IxCodeID=3, ProductCode="دج101" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="فورون فیروزه ای SG-400%", IxCodeID=8, ProductCode="دف102" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="فورون بنفش S-3RL", IxCodeID=2, ProductCode="دب102" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="فورون زرد RD-4GL", IxCodeID=4, ProductCode="دز105" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="سریلن قرمز BR-LS", IxCodeID=9, ProductCode="دق106" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="سریلن قرمز BD", IxCodeID=9, ProductCode="دق107" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="سریلن قرمز 2BL", IxCodeID=9, ProductCode="دق108" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="سریلن ردبراون RFS", IxCodeID=3, ProductCode="دج102" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="سریلن اسکارلت 2RLS", IxCodeID=13, ProductCode="دن101" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="سریلن سرمه ای GN", IxCodeID=8, ProductCode="دف103" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="فانتاگن قرمز BRL", IxCodeID=9, ProductCode="دق109" },
new Product {ProductCategoryID=2,UnitID=2,ProductName =" مشکی EX-SF 300%", IxCodeID=12, ProductCode="دم104" },
new Product {ProductCategoryID=2,UnitID=2,ProductName =" سرمه ای EX ", IxCodeID=8, ProductCode="دف104" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="فرانک کالر صورتی ", IxCodeID=6, ProductCode="دص102" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="سریلن قرمز 2BLS", IxCodeID=9, ProductCode="دق110" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="چینی مشکی SEG330%", IxCodeID=12, ProductCode="دم105" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="چینی سرمه ای HGLN 200%", IxCodeID=8, ProductCode="دف105" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="TIANچینی RED SE-GFL 200%", IxCodeID=9, ProductCode="دق111" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="TIANچینی BLUE HGL 200%", IxCodeID=1, ProductCode="دآ110" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="TIANچینی BLUE SGL 200%", IxCodeID=1, ProductCode="دآ111" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="TIANچینی BLUE SE-3R 200%", IxCodeID=1, ProductCode="دآ112" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="TIANچینی BROWN R 150%", IxCodeID=10, ProductCode="دک101" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="TIANچینی ORANGE S-2GFL 150%", IxCodeID=13, ProductCode="دن102" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="TIANچینی BLACK ECT 300%", IxCodeID=12, ProductCode="دم106" },
new Product {ProductCategoryID=2,UnitID=2,ProductName ="TIANچینی BLACK ECOR 360%", IxCodeID=12, ProductCode="دم107" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="سولفونیل آبی 4GL-N", IxCodeID=1, ProductCode="مآ101" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="سولفونیل آبی AGFL", IxCodeID=1, ProductCode="مآ102" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="سولفونیل نارنجی TGL", IxCodeID=13, ProductCode="من101" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="سولفونیل نارنجی TGN", IxCodeID=13, ProductCode="من102" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="سولفونیل قرمز 7BN", IxCodeID=9, ProductCode="مق101" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="سولفونیل قرمز BNL", IxCodeID=9, ProductCode="مق102" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="سولفونیل قرمز 2BN", IxCodeID=9, ProductCode="مق103" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="سولفونیل قرمز 3BL", IxCodeID=9, ProductCode="مق104" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="سولفونیل زرد FFL", IxCodeID=4, ProductCode="مز101" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="دی فنیل سرمه ای AB", IxCodeID=8, ProductCode="مف101" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="دایرکت آبی T (سیبا) ", IxCodeID=1, ProductCode="مآ103" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="دایرکت نارنجی T (سیبا) ", IxCodeID=13, ProductCode="من103" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" آبی 5B (آپولو) ", IxCodeID=1, ProductCode="مآ104" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" بردو B (آپولو) ", IxCodeID=3, ProductCode="مج101" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" فیروزه ای GL (آپولو) ", IxCodeID=8, ProductCode="مف102" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" سرمه ای 300% (اینترالیت) ", IxCodeID=8, ProductCode="مف103" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" بنفش 5B (اینترالیت) ", IxCodeID=2, ProductCode="مب101" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" مشکی VSF", IxCodeID=12, ProductCode="مم101" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" مشکی EX (چینی) ", IxCodeID=12, ProductCode="مم102" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" سرمه ای 1161", IxCodeID=8, ProductCode="مف104" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" اسکارلت 4BS", IxCodeID=13, ProductCode="من104" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" زرد 8G", IxCodeID=4, ProductCode="مز102" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" نارنجی WS (کلمبیا) ", IxCodeID=13, ProductCode="من105" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="سولار بریلیانت قرمز BA", IxCodeID=9, ProductCode="مق105" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" سبز BN", IxCodeID=5, ProductCode="مس101" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" قهوه ای MN", IxCodeID=10, ProductCode="مک101" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="سولار گلدن یلو R", IxCodeID=11, ProductCode="مگ101" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" قهوه ای FBA", IxCodeID=10, ProductCode="مک102" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" مشکی G", IxCodeID=12, ProductCode="مم103" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="دایرکت براون GTL", IxCodeID=10, ProductCode="مک103" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="دیازول نارنجی ", IxCodeID=13, ProductCode="من106" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="دیازول بنفش ", IxCodeID=2, ProductCode="مب102" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="Solarus Navy Blue B2R", IxCodeID=1, ProductCode="مآ105" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="سولفونیل قهوه ای RL -130%", IxCodeID=10, ProductCode="مک104" },
new Product {ProductCategoryID=3,UnitID=2,ProductName ="Sirius Blue S-BRR", IxCodeID=1, ProductCode="مآ106" },
new Product {ProductCategoryID=3,UnitID=2,ProductName =" Black 22  - 1200 VSF", IxCodeID=12, ProductCode="مم104" },
new Product {ProductCategoryID=4,UnitID=2,ProductName ="چینی Light Green 3", IxCodeID=5, ProductCode="گس101" },
new Product {ProductCategoryID=4,UnitID=2,ProductName ="چینی Red LGF 200%", IxCodeID=9, ProductCode="گق101" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" بردو 3B", IxCodeID=3, ProductCode="گج101" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" یلوبراون GDR", IxCodeID=4, ProductCode="گز101" },
new Product {ProductCategoryID=4,UnitID=2,ProductName ="سولفور قهوه ای GD", IxCodeID=10, ProductCode="گک101" },
new Product {ProductCategoryID=4,UnitID=2,ProductName ="چینی Blue 3R 130%", IxCodeID=1, ProductCode="گآ101" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" خاکی 2020", IxCodeID=10, ProductCode="گک102" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" نیوی 507", IxCodeID=8, ProductCode="گف101" },
new Product {ProductCategoryID=4,UnitID=2,ProductName ="چینی Yellow Brown 6GD 150%", IxCodeID=4, ProductCode="گز102" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" Yellow Brown 5G 150%", IxCodeID=4, ProductCode="گز103" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" یلوبراون 6G", IxCodeID=4, ProductCode="گز104" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" زرد GC 250%", IxCodeID=4, ProductCode="گز105" },
new Product {ProductCategoryID=4,UnitID=2,ProductName ="سولوزول (جیمز  رابینسون) نارنجی 6R", IxCodeID=13, ProductCode="گن101" },
new Product {ProductCategoryID=4,UnitID=2,ProductName ="سولفوزول قهوه ای B", IxCodeID=10, ProductCode="گک103" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" قهوه ای BRL", IxCodeID=10, ProductCode="گک104" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" سبز GCO", IxCodeID=5, ProductCode="گس102" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" سبز YN ", IxCodeID=5, ProductCode="گس103" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" خاکی TGD", IxCodeID=10, ProductCode="گک105" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" Blue CV 120%", IxCodeID=1, ProductCode="گآ102" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" Black B 230%", IxCodeID=12, ProductCode="گم101" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" Black BR 240%", IxCodeID=12, ProductCode="گم102" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" Dark Green 511 300%", IxCodeID=5, ProductCode="گس104" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" Dark Green 611 300%", IxCodeID=5, ProductCode="گس105" },
new Product {ProductCategoryID=4,UnitID=2,ProductName ="گوگردی مایع مشکی RC-SIVI", IxCodeID=12, ProductCode="گم103" },
new Product {ProductCategoryID=4,UnitID=2,ProductName =" Blue 507 180%", IxCodeID=1, ProductCode="گآ103" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="سیبانون آبی 2B مایع", IxCodeID=1, ProductCode="خآ101" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="سیبانون قهوه ای 3B", IxCodeID=10, ProductCode="خک101" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="سیبانون قهوه ای 2BR", IxCodeID=10, ProductCode="خک102" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="سیبانون خاکی 2G", IxCodeID=10, ProductCode="خک103" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="سیبانون آلیو S", IxCodeID=5, ProductCode="خس101" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="سیبانون آلیو B2G", IxCodeID=5, ProductCode="خس102" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="سیبانون نارنجی 3R مایع", IxCodeID=13, ProductCode="خن101" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="سیبانون صورتی 2R", IxCodeID=6, ProductCode="خص101" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="سیبانون زرد 3R مایع", IxCodeID=4, ProductCode="خز101" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="سیبانون یلوبراون G", IxCodeID=4, ProductCode="خز102" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="ایندانترن صورتی 3B مایع", IxCodeID=6, ProductCode="خص102" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="ایندانترن بنفش RR مایع", IxCodeID=2, ProductCode="خب101" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="Vat Black BB", IxCodeID=12, ProductCode="خم101" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="Vat Gray M", IxCodeID=12, ProductCode="خم102" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="ایندانترن بنفش RR Powder", IxCodeID=2, ProductCode="خب102" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="Vat Blue RSN (809)", IxCodeID=1, ProductCode="خآ102" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="Vat Dark Blue BO", IxCodeID=1, ProductCode="خآ103" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="Vat Dark Blue VB", IxCodeID=1, ProductCode="خآ104" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="Vat Brown BR", IxCodeID=10, ProductCode="خک104" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="Vat Olive Green B", IxCodeID=5, ProductCode="خس103" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="Vat Olive T", IxCodeID=5, ProductCode="خس104" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="Vat Red R", IxCodeID=9, ProductCode="خق101" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="Vat Yellow GCN", IxCodeID=4, ProductCode="خز103" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="سولانترن قرمز FB", IxCodeID=9, ProductCode="خق102" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="هیدرون بلو FG", IxCodeID=1, ProductCode="خآ105" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="Vat Black RB", IxCodeID=12, ProductCode="خم103" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="Vat Black 3B", IxCodeID=12, ProductCode="خم104" },
new Product {ProductCategoryID=5,UnitID=2,ProductName ="یوهانترن اسکارلت R", IxCodeID=13, ProductCode="خن102" },
new Product {ProductCategoryID=6,UnitID=2,ProductName ="چینی نیل ", IxCodeID=8, ProductCode="نف101" },
new Product {ProductCategoryID=6,UnitID=2,ProductName ="Dystar نیل ", IxCodeID=8, ProductCode="نف102" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="ایمپرون قهوه ای KRT", IxCodeID=10, ProductCode="پک101" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="ایمپرون سبز KG-125", IxCodeID=5, ProductCode="پس101" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="ایمپرون قرمز K-GR", IxCodeID=9, ProductCode="پق101" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="ایمپرون بنفش KB", IxCodeID=2, ProductCode="پب101" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="مینروا مشکی R", IxCodeID=12, ProductCode="پم101" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="مینروا سبز BBN", IxCodeID=5, ProductCode="پس102" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="مینروا آبی 5RF", IxCodeID=1, ProductCode="پآ101" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="مینروا آبی 2G", IxCodeID=1, ProductCode="پآ102" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="مینروا آبی B", IxCodeID=1, ProductCode="پآ103" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="مینروا گلدن 3R", IxCodeID=11, ProductCode="پگ101" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="مینروا قرمز 2G", IxCodeID=9, ProductCode="پق102" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="مینروا زرد 2G", IxCodeID=4, ProductCode="پز101" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="مینروا نارنجی 3RL", IxCodeID=13, ProductCode="پن101" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="هیلزارین آبی BGT", IxCodeID=1, ProductCode="پآ104" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="هیلزارین سبز BT", IxCodeID=5, ProductCode="پس103" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="پیگماست فسفری ", IxCodeID=7, ProductCode="پپ101" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="پیگماست مشکی KGF", IxCodeID=12, ProductCode="پم102" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="پیگماست قهوه ای KV", IxCodeID=10, ProductCode="پک102" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="پیگماست قرمز KB", IxCodeID=9, ProductCode="پق103" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="پیگماست نارنجی KG", IxCodeID=13, ProductCode="پن102" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="مینروا قرمز BTL", IxCodeID=9, ProductCode="پق104" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="کلاریانت مشکی H-TR", IxCodeID=12, ProductCode="پم103" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="پیگماست مشکی BD-T", IxCodeID=12, ProductCode="پم104" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="ایمپرون زرد K-2G", IxCodeID=4, ProductCode="پز102" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="چینی زرد FG(8202)", IxCodeID=4, ProductCode="پز103" },
new Product {ProductCategoryID=7,UnitID=2,ProductName ="چینی قهوه ای F2R(8801)", IxCodeID=10, ProductCode="پک103" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="سود مایع", IxCodeID=18, ProductCode="تگ101" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="اورینت ظاهر شونده", IxCodeID=15, ProductCode="تچ101" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="نرمکن پلی اتیلنی NP-825", IxCodeID=14, ProductCode="تت101" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="بیندر T-34 سیماب رزین", IxCodeID=15, ProductCode="تچ102" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="هیدروسولفیت BASF", IxCodeID=18, ProductCode="تگ102" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="نرمکن سیلیکونی SM-23", IxCodeID=14, ProductCode="تت102" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="اسید استیک", IxCodeID=19, ProductCode="تم101" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="تثبیت کننده ترنسفر TF-232", IxCodeID=16, ProductCode="تر101" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="آنزیم Ecostone A200", IxCodeID=19, ProductCode="تم102" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="احیاء کننده TF-110B", IxCodeID=16, ProductCode="تر102" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="غلظت دهنده S-240HV", IxCodeID=15, ProductCode="تچ103" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="سولفور", IxCodeID=16, ProductCode="تر103" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="عامل پخت TF-125", IxCodeID=19, ProductCode="تم103" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="کربنات سبک", IxCodeID=16, ProductCode="تر104" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="رزین DM", IxCodeID=17, ProductCode="تص101" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="صابون شستشوی رآکتیو - Neutral Soapine Agent TF-230", IxCodeID=16, ProductCode="تر105" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="آب اکسیژنه", IxCodeID=19, ProductCode="تم104" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="پیگمنت سفید", IxCodeID=15, ProductCode="تچ104" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="نفوذ دهنده TF-107C", IxCodeID=18, ProductCode="تگ103" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="پلی تری فسفات سدیم", IxCodeID=16, ProductCode="تر106" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="گلیسیرین", IxCodeID=15, ProductCode="تچ105" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="اسید سولفوریک", IxCodeID=17, ProductCode="تص102" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="ضد شکستگی TF-208C", IxCodeID=16, ProductCode="تر107" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="TF-101 Oilremover", IxCodeID=19, ProductCode="تم105" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="دیسپرس کننده TF-510", IxCodeID=16, ProductCode="تر108" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="ضدکف TF-508/508C", IxCodeID=18, ProductCode="تگ104" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="صابون مول 10", IxCodeID=19, ProductCode="تم106" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="اسید سولفونیک L", IxCodeID=19, ProductCode="تم107" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="بوتیل استات", IxCodeID=15, ProductCode="تچ106" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="Safolite", IxCodeID=15, ProductCode="تچ107" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="سولفات آلومینیوم", IxCodeID=17, ProductCode="تص103" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="اوره صنعتی", IxCodeID=18, ProductCode="تگ105" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="اشتابیلایزر ترکیه - AntiOxidante", IxCodeID=16, ProductCode="تر109" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="کریر RC-152", IxCodeID=16, ProductCode="تر110" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="Dispersing Agent Na-Na mol", IxCodeID=16, ProductCode="تر111" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="غلظت دهنده تری پرینت P.T", IxCodeID=15, ProductCode="تچ108" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="آنزیم ترنسفر TF-162F", IxCodeID=19, ProductCode="تم108" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="یکنواخت کننده رنگ رآکتیو لیافام شیمی SARAKOLRLC", IxCodeID=16, ProductCode="تر112" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="اورینت پلاستیک", IxCodeID=15, ProductCode="تچ109" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="نرمکن سیلیکونی TF-432", IxCodeID=14, ProductCode="تت103" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="نرمکن سیلیکونی TF-431", IxCodeID=14, ProductCode="تت104" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="پایدارکننده TF-122", IxCodeID=19, ProductCode="تم109" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="پلی وینیل الکل", IxCodeID=15, ProductCode="تچ110" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="صابون Polywash RF-792", IxCodeID=16, ProductCode="تر113" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="سفید کن پلی استر CPS-D", IxCodeID=16, ProductCode="تر114" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="اشتابیلایزر TS", IxCodeID=16, ProductCode="تر115" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="غلظت دهنده اسیدی NA-600HV", IxCodeID=15, ProductCode="تچ111" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="پرکلرین", IxCodeID=15, ProductCode="تچ112" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="امولسیون کننده چربی گیر TF-128", IxCodeID=19, ProductCode="تم110" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="اسید کلریدریک (جوهر نمک)", IxCodeID=18, ProductCode="تگ106" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="Emulgator Perigen W190", IxCodeID=15, ProductCode="تچ113" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="سفیدکن VBL", IxCodeID=16, ProductCode="تر116" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="عمق دهنده Samtex 55w-3", IxCodeID=14, ProductCode="تت105" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="متالیک صدف - 1100B", IxCodeID=15, ProductCode="تچ114" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="سوپرفسفات", IxCodeID=17, ProductCode="تص104" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="Emulgator ساخت آلمان", IxCodeID=15, ProductCode="تچ115" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="اسید کرومیک", IxCodeID=15, ProductCode="تچ116" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="سولفات سدیم", IxCodeID=16, ProductCode="تر117" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="گلوکز", IxCodeID=16, ProductCode="تر118" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="آلجینات", IxCodeID=15, ProductCode="تچ117" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="آب ژاول", IxCodeID=18, ProductCode="تگ107" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="Uvitex BHT", IxCodeID=16, ProductCode="تر119" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="صابون شستشو HiClean 878T", IxCodeID=16, ProductCode="تر120" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="غلظت دهنده Mayprogum R600", IxCodeID=15, ProductCode="تچ118" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="یکنواخت کننده رنگ رآکتیو رزفام - RF-801", IxCodeID=16, ProductCode="تر121" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="متاللیک برنز 2018", IxCodeID=15, ProductCode="تچ119" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="رنگالیت Rongalit C", IxCodeID=15, ProductCode="تچ120" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="پرمنگنات", IxCodeID=16, ProductCode="تر122" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="سفید کن پلی استر Sunwhite SP", IxCodeID=16, ProductCode="تر123" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="Denires Cube-ML", IxCodeID=15, ProductCode="تچ121" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="Denicoat 16-x", IxCodeID=15, ProductCode="تچ122" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="غلظت دهنده اسیدی GUARANTE", IxCodeID=15, ProductCode="تچ123" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="اسید اگزالیک", IxCodeID=16, ProductCode="تر124" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="تثبیت کننده Tubifix ML55", IxCodeID=15, ProductCode="تچ124" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="نرمکن سیلیکونی TFS0A1", IxCodeID=14, ProductCode="تت106" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="رزیست سالت", IxCodeID=15, ProductCode="تچ125" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="نرمکن کاتیونیک TF-441", IxCodeID=14, ProductCode="تت107" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="امولسیفایر TF-MS0A1", IxCodeID=14, ProductCode="تت108" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="بیندر فلوک NC-017", IxCodeID=15, ProductCode="تچ126" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="تقلیل وزن TF-1181", IxCodeID=19, ProductCode="تم111" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="بی کربنات سدیم (جوش شیرین)", IxCodeID=18, ProductCode="تگ108" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="سولفات آمونیوم", IxCodeID=18, ProductCode="تگ109" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="سیلیکات", IxCodeID=16, ProductCode="تر125" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="تیتانیوم دی اکساید KEMIRA 650", IxCodeID=15, ProductCode="تچ127" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="دکسترین قلیایی - MaltoDextrin", IxCodeID=15, ProductCode="تچ128" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="اسید فرمیک", IxCodeID=18, ProductCode="تگ110" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="ضدآب Orgall Ard Fe1112", IxCodeID=14, ProductCode="تت109" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="پایدارکننده سفیدگری Rucogen-WBL", IxCodeID=19, ProductCode="تم112" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="TF-428 Elastic Finishing Agent", IxCodeID=14, ProductCode="تت110" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="چسب فلوک  Orgal 83", IxCodeID=15, ProductCode="تچ129" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="روغن DOP", IxCodeID=15, ProductCode="تچ130" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="غلظت دهنده فلوک Orgal M420", IxCodeID=15, ProductCode="تچ131" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="PVC", IxCodeID=15, ProductCode="تچ132" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="SETAFEN PEN", IxCodeID=18, ProductCode="تگ111" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="Desizing Agent TF-127", IxCodeID=14, ProductCode="تت111" },
new Product {ProductCategoryID=8,UnitID=2,ProductName ="آنتی اکسیدانت", IxCodeID=16, ProductCode="تر126" },

            };
            Products.ForEach(a => context.Products.Add(a));
            context.SaveChanges();


        }

    }
}