// <auto-generated />
namespace Anbar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_AddComputedFieldsToTranDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_AddComputedFieldsToTranDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201511150820283_Create_AddComputedFieldsToTranDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
