// <auto-generated />
namespace Anbar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IxCodeNameStrLengthTo70 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IxCodeNameStrLengthTo70));
        
        string IMigrationMetadata.Id
        {
            get { return "201511220931032_IxCodeName-StrLengthTo70"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
